packages:
  - "."

overrides:
  remotion: 4.0.484
  "@remotion/player": 4.0.484
  "@remotion/transitions": 4.0.484
  "@remotion/paths": 4.0.484
  "@remotion/shapes": 4.0.484
  "@remotion/media-utils": 4.0.484
  "@remotion/three": 4.0.484
